#
#   ░██████╗░█████╗░███╗░░██╗████████╗██╗██████╗░░█████╗░████████╗
#    ██╔════╝██╔══██╗████╗░██║╚══██╔══╝██║██╔══██╗██╔══██╗╚══██╔══╝
#    ╚█████╗░███████║██╔██╗██║░░░██║░░░██║██████╦╝██║░░██║░░░██║░░░
#    ░╚═══██╗██╔══██║██║╚████║░░░██║░░░██║██╔══██╗██║░░██║░░░██║░░░
#    ██████╔╝██║░░██║██║░╚███║░░░██║░░░██║██████╦╝╚█████╔╝░░░██║░░░
#    ╚═════╝░╚═╝░░╚═╝╚═╝░░╚══╝░░░╚═╝░░░╚═╝╚═════╝░░╚════╝░░░░╚═╝░░░
#
#    АВТОР ПЛАГИНА - skully [ https://skully.space ]
#
bots:
  nicks:
    - "Evolution"
    - "FaithCoreTop"
    - "MCStorm"
  command: "kick %player% Вы подозреваетесь в бот атаке"

messages:
  telegram:
    bot: "❗️❗️❗️ Замечена бот атака❗️❗️❗️%0AС ником 🤖%bot%🤖%0AЗабанен был 💥%nick%💥%0AС любовью SAntiBot♥️"

telegram:
  alert:
    name: true
  bot:
    token: "СЮДА ВАШ ТОКЕН ОТ BotFather"
    ids:
      - "СЮДА ВАШ АЙДИ В ТГ"
      - "СЮДА ВАШ АЙДИ В ТГ"